
name           = "StrongPNT"
version        = "0.1.0"
defaultTargets = ["StrongPNT"]

[leanOptions]
pp.unicode.fun         = true
autoImplicit           = false
relaxedAutoImplicit    = false
linter.unusedVariables = false
linter.unusedSimpArgs = false

[[lean_lib]]
name = "StrongPNT"

[[require]]
name  = "mathlib"
scope = "leanprover-community"
rev   = "v4.22.0"

[[require]]
name = "PrimeNumberTheoremAnd"
git  = "https://github.com/AlexKontorovich/PrimeNumberTheoremAnd.git"
rev  = "c4f86ebe040d82d1a55a4c88c368825d5a02a573"

[[require]]
name = "checkdecls"
git  = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git  = "https://github.com/leanprover/doc-gen4"
rev  = "v4.22.0"
