
name           = "StrongPNT"
version        = "0.1.0"
defaultTargets = ["StrongPNT"]

[leanOptions]
pp.unicode.fun         = true
autoImplicit           = false
relaxedAutoImplicit    = false
linter.mathlibStandardSet = true
linter.style.header = false
linter.style.longLine = false
linter.style.emptyLine = false

[[lean_lib]]
name = "StrongPNT"

[[require]]
name  = "mathlib"
scope = "leanprover-community"
rev = "e83933a68d217ebc2220a"

[[require]]
name = "PrimeNumberTheoremAnd"
git  = "https://github.com/alexKontorovich/PrimeNumberTheoremAnd.git"
rev = "v4.34.0"

[[require]]
name = "checkdecls"
git  = "https://github.com/PatrickMassot/checkdecls.git"
