
name           = "StrongPNT"
version        = "0.1.0"
defaultTargets = ["StrongPNT"]

[leanOptions]
pp.unicode.fun         = true
autoImplicit           = false
relaxedAutoImplicit    = false
linter.unusedVariables = false

[[lean_lib]]
name = "StrongPNT"

[[require]]
name  = "mathlib"
scope = "leanprover-community"
rev   = "v4.21.0"

[[require]]
name = "PrimeNumberTheoremAnd"
git  = "https://github.com/AlexKontorovich/PrimeNumberTheoremAnd.git"
rev  = "47f29a1e5a4fe1daf5c3f8c5fc8408626e95fda5"

[[require]]
name = "checkdecls"
git  = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git  = "https://github.com/leanprover/doc-gen4"
rev  = "v4.21.0"
